# Generated by Django 3.1.4 on 2020-12-13 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDamoa',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=50)),
                ('now', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('seller', models.CharField(max_length=15)),
                ('category', models.CharField(default='', max_length=20)),
                ('bid_unit', models.IntegerField(default=0)),
                ('bid_start', models.DateTimeField(default=datetime.datetime(2020, 12, 14, 2, 39, 48, 707712))),
                ('bid_end', models.DateTimeField(default=datetime.datetime(2020, 12, 14, 2, 39, 48, 707712))),
                ('price', models.IntegerField()),
                ('now_price', models.IntegerField(default=0)),
                ('likey', models.IntegerField(default=0)),
                ('img', models.ImageField(default='', upload_to='images/')),
                ('user_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.userdamoa')),
            ],
            options={
                'unique_together': {('user_id', 'prod_id')},
            },
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField(default=0)),
                ('bid_end', models.IntegerField(default=0)),
                ('bid_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.userdamoa')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
                ('user_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.userdamoa')),
            ],
            options={
                'unique_together': {('user_id', 'prod_id')},
            },
        ),
    ]
