# Generated by Django 3.1.4 on 2020-12-13 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201214_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 2, 40, 27, 680797)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 2, 40, 27, 679796)),
        ),
    ]
