# Generated by Django 3.1.4 on 2020-12-14 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201214_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdamoa',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 12, 2, 47, 850836)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 12, 2, 47, 850836)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
                ('user_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.userdamoa')),
            ],
        ),
    ]
