# Generated by Django 3.1.4 on 2020-12-14 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201214_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdamoa',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 12, 45, 45, 340478)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 12, 45, 45, 340478)),
        ),
    ]
