# Generated by Django 3.1.4 on 2020-12-18 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201218_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 16, 55, 30, 821803)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 16, 55, 30, 821803)),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
                ('user_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.userdamoa')),
            ],
            options={
                'unique_together': {('user_id', 'prod_id')},
            },
        ),
    ]
