# Generated by Django 3.1.4 on 2020-12-18 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201218_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='now_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 17, 27, 40, 827108)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 17, 27, 40, 827108)),
        ),
    ]
