# Generated by Django 3.1.4 on 2020-12-18 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201218_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='now_buyer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 17, 32, 43, 28677)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 17, 32, 43, 28677)),
        ),
    ]
