# Generated by Django 3.1.4 on 2020-12-18 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20201218_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='now_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 17, 52, 18, 39928)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 17, 52, 18, 39928)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 17, 52, 18, 39928)),
        ),
    ]
