# Generated by Django 3.1.4 on 2020-12-19 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20201218_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdamoa',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 16, 2, 52, 882216)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 16, 2, 52, 882216)),
        ),
        migrations.AlterField(
            model_name='product',
            name='now_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 16, 2, 52, 882216)),
        ),
    ]
