# Generated by Django 3.1.4 on 2020-12-19 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20201219_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reply_content',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='report',
            name='reply_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 0, 50, 55, 901816)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 0, 50, 55, 901816)),
        ),
        migrations.AlterField(
            model_name='product',
            name='now_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 0, 50, 55, 901816)),
        ),
    ]
