# Generated by Django 3.1.4 on 2020-12-19 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20201220_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reply_title',
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 42, 7, 356323)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 42, 7, 356323)),
        ),
        migrations.AlterField(
            model_name='product',
            name='now_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 42, 7, 356323)),
        ),
    ]
