# Generated by Django 3.1.4 on 2020-12-19 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20201220_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reply',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 43, 21, 344127)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 43, 21, 344127)),
        ),
        migrations.AlterField(
            model_name='product',
            name='now_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 43, 21, 344127)),
        ),
    ]
