# Generated by Django 3.1.4 on 2020-12-21 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20201221_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='reply_content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 13, 19, 51, 137360)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 13, 19, 51, 137360)),
        ),
        migrations.AlterField(
            model_name='product',
            name='now_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 13, 19, 51, 137360)),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
