# Generated by Django 3.1.4 on 2020-12-21 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20201221_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 0, 25, 28, 49760)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 0, 25, 28, 49760)),
        ),
        migrations.AlterField(
            model_name='product',
            name='now_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 0, 25, 28, 49760)),
        ),
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
